services:
  # Development services
  postgres:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: streakbond
      POSTGRES_PASSWORD: "p5cnk1uayQXksW_Hy57CAPhFvfEP8O4w"
    volumes:
      - streakbond_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "UUOWrBBJzrCDl55_uCkIrHTyGmJQhxcl"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: streakbond_test
      POSTGRES_PASSWORD: "U2_fc53B0x2Zgn6999flizq6v19xY4H7"
    volumes:
      - streakbond_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "laN6Xq8MMFYJBOnVynlTILaAjy09OQGo"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  streakbond_data:
  streakbond_test_data:
